-- AlterTable
ALTER TABLE "check_ins" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "gyms" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT;
